registry:
   url: http://registry:5000/v2
   name: localhost
   readonly: false
  # with this config the user will not see all the available repos in docker-registry-web
   show-permitted-repo-only: true
   auth:
     enabled: true
     key: /conf/auth.key
     issuer: test
